AllCops:
  Include:
    - Rakefile
    - Gemfile

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
